In [1]:
from lakehouse_sdk import execute_asset, clear_cache
import polars as pl

In [5]:
clear_cache()

🗑️  Cache limpiado

In [2]:
stg_s2p_leads = execute_asset("stg_s2p_leads", partition_key="2024-12-01")
stg_s2p_alg_activity_log_projects = execute_asset("stg_s2p_alg_activity_log_projects", partition_key="2024-12-01")
stg_s2p_apd_appointment_dates = execute_asset("stg_s2p_apd_appointment_dates", partition_key="2024-12-01")
stg_s2p_appointments = execute_asset("stg_s2p_appointments", partition_key="2024-12-01")
stg_s2p_leh_lead_event_histories = execute_asset("stg_s2p_leh_lead_event_histories", partition_key="2024-12-01")
stg_s2p_projects = execute_asset("stg_s2p_projects", partition_key="2024-12-01")
stg_s2p_user_profiles = execute_asset("stg_s2p_user_profiles", partition_key="2024-12-01")
stg_s2p_prs_project_spots = execute_asset("stg_s2p_prs_project_spots", partition_key="2024-12-01")

🔗 Resolviendo dependencias para stg_s2p_leads: ['raw_s2p_clients']

2026-01-07 15:39:03 -0600 - dagster - INFO - system - Using schema overrides for 89 columns
2026-01-07 15:39:06 -0600 - dagster - INFO - system - Extracted 61069 rows from MySQL (polars read_database with schema)
2026-01-07 15:39:06 -0600 - dagster - INFO - system - raw_s2p_clients: 61069 rows for 2024-12-01
2026-01-07 15:39:06 -0600 - dagster - INFO - system - stg_s2p_leads: 61069 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_alg_activity_log_projects: ['raw_s2p_activity_log_projects']

2026-01-07 15:39:07 -0600 - dagster - INFO - system - Using schema overrides for 16 columns
2026-01-07 15:39:10 -0600 - dagster - INFO - system - Extracted 2475 rows from MySQL (polars read_database with schema)
2026-01-07 15:39:10 -0600 - dagster - INFO - system - raw_s2p_activity_log_projects: 2475 rows for 2024-12-01
2026-01-07 15:39:10 -0600 - dagster - INFO - system - stg_s2p_alg_activity_log_projects: 2475 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_apd_appointment_dates: ['raw_s2p_calendar_appointment_dates']

2026-01-07 15:39:12 -0600 - dagster - INFO - system - Using schema overrides for 15 columns
2026-01-07 15:39:13 -0600 - dagster - INFO - system - Extracted 9296 rows from MySQL (polars read_database with schema)
2026-01-07 15:39:13 -0600 - dagster - INFO - system - raw_s2p_calendar_appointment_dates: 9296 rows for 2024-12-01
2026-01-07 15:39:13 -0600 - dagster - INFO - system - stg_s2p_apd_appointment_dates: 9296 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_appointments: ['raw_s2p_calendar_appointments']

2026-01-07 15:39:14 -0600 - dagster - INFO - system - Using schema overrides for 15 columns
2026-01-07 15:39:16 -0600 - dagster - INFO - system - Extracted 6303 rows from MySQL (polars read_database with schema)
2026-01-07 15:39:16 -0600 - dagster - INFO - system - raw_s2p_calendar_appointments: 6303 rows for 2024-12-01
2026-01-07 15:39:16 -0600 - dagster - INFO - system - stg_s2p_appointments: 6303 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_leh_lead_event_histories: ['raw_s2p_client_event_histories']

2026-01-07 15:39:17 -0600 - dagster - INFO - system - Using schema overrides for 9 columns
2026-01-07 15:39:19 -0600 - dagster - INFO - system - Extracted 107744 rows from MySQL (polars read_database with schema)
2026-01-07 15:39:19 -0600 - dagster - INFO - system - raw_s2p_client_event_histories: 107744 rows for 2024-12-01
2026-01-07 15:39:19 -0600 - dagster - INFO - system - stg_s2p_leh_lead_event_histories: 107744 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_projects: ['raw_s2p_project_requirements']

2026-01-07 15:39:20 -0600 - dagster - INFO - system - Using schema overrides for 40 columns
2026-01-07 15:39:22 -0600 - dagster - INFO - system - Extracted 19820 rows from MySQL (polars read_database with schema)
2026-01-07 15:39:22 -0600 - dagster - INFO - system - raw_s2p_project_requirements: 19820 rows for 2024-12-01
2026-01-07 15:39:22 -0600 - dagster - INFO - system - stg_s2p_projects: 19820 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_user_profiles: ['raw_s2p_profiles']

2026-01-07 15:39:23 -0600 - dagster - INFO - system - Using schema overrides for 22 columns
2026-01-07 15:39:25 -0600 - dagster - INFO - system - Extracted 21926 rows from MySQL (polars read_database with schema)
2026-01-07 15:39:25 -0600 - dagster - INFO - system - raw_s2p_profiles: 21926 rows for 2024-12-01
2026-01-07 15:39:25 -0600 - dagster - INFO - system - stg_s2p_user_profiles: 21925 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_prs_project_spots: ['raw_s2p_project_requirement_spots']

2026-01-07 15:39:26 -0600 - dagster - INFO - system - Using schema overrides for 19 columns
2026-01-07 15:39:28 -0600 - dagster - INFO - system - Extracted 84236 rows from MySQL (polars read_database with schema)
2026-01-07 15:39:28 -0600 - dagster - INFO - system - raw_s2p_project_requirement_spots: 84236 rows for 2024-12-01
2026-01-07 15:39:28 -0600 - dagster - INFO - system - stg_s2p_prs_project_spots: 84133 rows for partition 2024-12-01

In [2]:
df_lds = execute_asset("gold_bt_lds_lead_spots", partition_key="2024-12-01")
df_lds

🔗 Resolviendo dependencias para gold_bt_lds_lead_spots: ['stg_s2p_leads', 'stg_s2p_projects', 'stg_s2p_prs_project_spots', 'stg_s2p_appointments', 'stg_s2p_apd_appointment_dates', 'stg_s2p_alg_activity_log_projects', 'stg_s2p_user_profiles']
🔗 Resolviendo dependencias para stg_s2p_leads: ['raw_s2p_clients']

2026-01-07 18:08:07 -0600 - dagster - INFO - system - Using schema overrides for 89 columns
2026-01-07 18:08:10 -0600 - dagster - INFO - system - Extracted 61085 rows from MySQL (polars read_database with schema)
2026-01-07 18:08:10 -0600 - dagster - INFO - system - raw_s2p_clients: 61085 rows for 2024-12-01
2026-01-07 18:08:10 -0600 - dagster - INFO - system - stg_s2p_leads: 61085 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_projects: ['raw_s2p_project_requirements']

2026-01-07 18:08:11 -0600 - dagster - INFO - system - Using schema overrides for 40 columns
2026-01-07 18:08:13 -0600 - dagster - INFO - system - Extracted 19833 rows from MySQL (polars read_database with schema)
2026-01-07 18:08:13 -0600 - dagster - INFO - system - raw_s2p_project_requirements: 19833 rows for 2024-12-01
2026-01-07 18:08:13 -0600 - dagster - INFO - system - stg_s2p_projects: 19833 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_prs_project_spots: ['raw_s2p_project_requirement_spots']

2026-01-07 18:08:14 -0600 - dagster - INFO - system - Using schema overrides for 19 columns
2026-01-07 18:08:15 -0600 - dagster - INFO - system - Extracted 84280 rows from MySQL (polars read_database with schema)
2026-01-07 18:08:15 -0600 - dagster - INFO - system - raw_s2p_project_requirement_spots: 84280 rows for 2024-12-01
2026-01-07 18:08:16 -0600 - dagster - INFO - system - stg_s2p_prs_project_spots: 84177 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_appointments: ['raw_s2p_calendar_appointments']

2026-01-07 18:08:17 -0600 - dagster - INFO - system - Using schema overrides for 15 columns
2026-01-07 18:08:18 -0600 - dagster - INFO - system - Extracted 6314 rows from MySQL (polars read_database with schema)
2026-01-07 18:08:18 -0600 - dagster - INFO - system - raw_s2p_calendar_appointments: 6314 rows for 2024-12-01
2026-01-07 18:08:18 -0600 - dagster - INFO - system - stg_s2p_appointments: 6314 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_apd_appointment_dates: ['raw_s2p_calendar_appointment_dates']

2026-01-07 18:08:19 -0600 - dagster - INFO - system - Using schema overrides for 15 columns
2026-01-07 18:08:20 -0600 - dagster - INFO - system - Extracted 9308 rows from MySQL (polars read_database with schema)
2026-01-07 18:08:20 -0600 - dagster - INFO - system - raw_s2p_calendar_appointment_dates: 9308 rows for 2024-12-01
2026-01-07 18:08:20 -0600 - dagster - INFO - system - stg_s2p_apd_appointment_dates: 9308 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_alg_activity_log_projects: ['raw_s2p_activity_log_projects']

2026-01-07 18:08:22 -0600 - dagster - INFO - system - Using schema overrides for 16 columns
2026-01-07 18:08:23 -0600 - dagster - INFO - system - Extracted 2476 rows from MySQL (polars read_database with schema)
2026-01-07 18:08:23 -0600 - dagster - INFO - system - raw_s2p_activity_log_projects: 2476 rows for 2024-12-01
2026-01-07 18:08:23 -0600 - dagster - INFO - system - stg_s2p_alg_activity_log_projects: 2476 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_user_profiles: ['raw_s2p_profiles']

2026-01-07 18:08:24 -0600 - dagster - INFO - system - Using schema overrides for 22 columns
2026-01-07 18:08:26 -0600 - dagster - INFO - system - Extracted 21929 rows from MySQL (polars read_database with schema)
2026-01-07 18:08:26 -0600 - dagster - INFO - system - raw_s2p_profiles: 21929 rows for 2024-12-01
2026-01-07 18:08:26 -0600 - dagster - INFO - system - stg_s2p_user_profiles: 21928 rows for partition 2024-12-01
2026-01-07 18:08:26 -0600 - dagster - INFO - system - gold_bt_lds_lead_spots: 155561 rows for partition 2024-12-01

shape: (155_561, 26)
┌─────────┬────────────┬─────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ lead_id ┆ project_id ┆ spot_id ┆ appointmen ┆ … ┆ aud_insert ┆ aud_updat ┆ aud_updat ┆ aud_job   │
│ ---     ┆ ---        ┆ ---     ┆ t_id       ┆   ┆ ed_date    ┆ ed_at     ┆ ed_date   ┆ ---       │
│ i64     ┆ i64        ┆ i64     ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ str       │
│         ┆            ┆         ┆ i64        ┆   ┆ date       ┆ datetime[ ┆ date      ┆           │
│         ┆            ┆         ┆            ┆   ┆            ┆ μs]       ┆           ┆           │
╞═════════╪════════════╪═════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 6       ┆ null       ┆ null    ┆ null       ┆ … ┆ 2026-01-07 ┆ 2026-01-0 ┆ 2026-01-0 ┆ gold_bt_l │
│         ┆            ┆         ┆            ┆   ┆            ┆ 7 18:08:2 ┆ 7         ┆ ds_lead_s │
│         ┆            ┆         ┆            ┆   ┆            ┆ 6.098666  ┆           ┆ pots      │
│ 7       ┆ null       ┆ null    ┆ null       ┆ … ┆ 2026-01-07 ┆ 2026-01-0 ┆ 2026-01-0 ┆ gold_bt_l │
│         ┆            ┆         ┆            ┆   ┆            ┆ 7 18:08:2 ┆ 7         ┆ ds_lead_s │
│         ┆            ┆         ┆            ┆   ┆            ┆ 6.098666  ┆           ┆ pots      │
│ 8       ┆ null       ┆ null    ┆ null       ┆ … ┆ 2026-01-07 ┆ 2026-01-0 ┆ 2026-01-0 ┆ gold_bt_l │
│         ┆            ┆         ┆            ┆   ┆            ┆ 7 18:08:2 ┆ 7         ┆ ds_lead_s │
│         ┆            ┆         ┆            ┆   ┆            ┆ 6.098666  ┆           ┆ pots      │
│ 9       ┆ null       ┆ null    ┆ null       ┆ … ┆ 2026-01-07 ┆ 2026-01-0 ┆ 2026-01-0 ┆ gold_bt_l │
│         ┆            ┆         ┆            ┆   ┆            ┆ 7 18:08:2 ┆ 7         ┆ ds_lead_s │
│         ┆            ┆         ┆            ┆   ┆            ┆ 6.098666  ┆           ┆ pots      │
│ 10      ┆ null       ┆ null    ┆ null       ┆ … ┆ 2026-01-07 ┆ 2026-01-0 ┆ 2026-01-0 ┆ gold_bt_l │
│         ┆            ┆         ┆            ┆   ┆            ┆ 7 18:08:2 ┆ 7         ┆ ds_lead_s │
│         ┆            ┆         ┆            ┆   ┆            ┆ 6.098666  ┆           ┆ pots      │
│ …       ┆ …          ┆ …       ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 27031   ┆ 3920       ┆ null    ┆ null       ┆ … ┆ 2026-01-07 ┆ 2026-01-0 ┆ 2026-01-0 ┆ gold_bt_l │
│         ┆            ┆         ┆            ┆   ┆            ┆ 7 18:08:2 ┆ 7         ┆ ds_lead_s │
│         ┆            ┆         ┆            ┆   ┆            ┆ 6.098666  ┆           ┆ pots      │
│ 23188   ┆ 5706       ┆ null    ┆ null       ┆ … ┆ 2026-01-07 ┆ 2026-01-0 ┆ 2026-01-0 ┆ gold_bt_l │
│         ┆            ┆         ┆            ┆   ┆            ┆ 7 18:08:2 ┆ 7         ┆ ds_lead_s │
│         ┆            ┆         ┆            ┆   ┆            ┆ 6.098666  ┆           ┆ pots      │
│ 27722   ┆ 8896       ┆ null    ┆ null       ┆ … ┆ 2026-01-07 ┆ 2026-01-0 ┆ 2026-01-0 ┆ gold_bt_l │
│         ┆            ┆         ┆            ┆   ┆            ┆ 7 18:08:2 ┆ 7         ┆ ds_lead_s │
│         ┆            ┆         ┆            ┆   ┆            ┆ 6.098666  ┆           ┆ pots      │
│ 4137    ┆ 608        ┆ null    ┆ null       ┆ … ┆ 2026-01-07 ┆ 2026-01-0 ┆ 2026-01-0 ┆ gold_bt_l │
│         ┆            ┆         ┆            ┆   ┆            ┆ 7 18:08:2 ┆ 7         ┆ ds_lead_s │
│         ┆            ┆         ┆            ┆   ┆            ┆ 6.098666  ┆           ┆ pots      │
│ 11364   ┆ 1471       ┆ null    ┆ null       ┆ … ┆ 2026-01-07 ┆ 2026-01-0 ┆ 2026-01-0 ┆ gold_bt_l │
│         ┆            ┆         ┆            ┆   ┆            ┆ 7 18:08:2 ┆ 7         ┆ ds_lead_s │
│         ┆            ┆         ┆            ┆   ┆            ┆ 6.098666  ┆           ┆ pots      │
└─────────┴────────────┴─────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [6]:
df_lds.filter(pl.col("lds_event_id") == 2)["lead_id"].n_unique()

17922

In [5]:
df_lds.filter(pl.col("lds_event_id") == 2)["lead_id"].count()

19595

In [9]:
df_funnel

shape: (38_413, 27)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ lpf_lead_ ┆ project_c ┆ lpf_visit ┆ lpf_visit ┆ … ┆ project_d ┆ lpf_flow ┆ lpf_event ┆ lead_prof │
│ date      ┆ reated_da ┆ _created_ ┆ _created_ ┆   ┆ isable_re ┆ ---      ┆ ---       ┆ iling_com │
│ ---       ┆ te        ┆ date      ┆ per_proje ┆   ┆ ason      ┆ str      ┆ str       ┆ pleted_at │
│ date      ┆ ---       ┆ ---       ┆ ct_…      ┆   ┆ ---       ┆          ┆           ┆ ---       │
│           ┆ date      ┆ date      ┆ ---       ┆   ┆ str       ┆          ┆           ┆ datetime[ │
│           ┆           ┆           ┆ date      ┆   ┆           ┆          ┆           ┆ μs]       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 2024-02-1 ┆ 2024-02-1 ┆ 2023-10-1 ┆ 2024-02-1 ┆ … ┆ Stopped   ┆ null     ┆ null      ┆ null      │
│ 3         ┆ 3         ┆ 1         ┆ 3         ┆   ┆ respondin ┆          ┆           ┆           │
│           ┆           ┆           ┆           ┆   ┆ g         ┆          ┆           ┆           │
│ 2024-10-0 ┆ 2024-10-0 ┆ 2023-11-0 ┆ 2024-10-0 ┆ … ┆ Won       ┆ null     ┆ null      ┆ null      │
│ 8         ┆ 8         ┆ 7         ┆ 8         ┆   ┆           ┆          ┆           ┆           │
│ 2024-01-2 ┆ 2024-01-2 ┆ 2023-12-0 ┆ 2024-01-2 ┆ … ┆ Won       ┆ null     ┆ null      ┆ null      │
│ 3         ┆ 3         ┆ 7         ┆ 3         ┆   ┆           ┆          ┆           ┆           │
│ 2024-01-0 ┆ 2024-02-1 ┆ 2023-12-1 ┆ 2024-02-1 ┆ … ┆ Project   ┆ null     ┆ null      ┆ null      │
│ 4         ┆ 3         ┆ 5         ┆ 3         ┆   ┆ deleted   ┆          ┆           ┆           │
│ 2024-01-0 ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null     ┆ null      ┆ null      │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      ┆ … ┆ Not appli ┆ L2       ┆ whatsappI ┆ 2025-12-1 │
│ 4         ┆ 4         ┆           ┆           ┆   ┆ cable     ┆          ┆ nteractio ┆ 4         │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ n         ┆ 17:13:53  │
│ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      ┆ … ┆ Not appli ┆ L2       ┆ whatsappI ┆ 2025-12-1 │
│ 4         ┆ 4         ┆           ┆           ┆   ┆ cable     ┆          ┆ nteractio ┆ 4         │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ n         ┆ 17:53:49  │
│ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      ┆ … ┆ Not appli ┆ L2       ┆ whatsappI ┆ null      │
│ 4         ┆ 4         ┆           ┆           ┆   ┆ cable     ┆          ┆ nteractio ┆           │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ n         ┆           │
│ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      ┆ … ┆ Not appli ┆ L2       ┆ whatsappI ┆ 2025-12-1 │
│ 4         ┆ 4         ┆           ┆           ┆   ┆ cable     ┆          ┆ nteractio ┆ 4         │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ n         ┆ 20:50:19  │
│ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      ┆ … ┆ Not appli ┆ L2       ┆ whatsappI ┆ 2025-12-1 │
│ 4         ┆ 4         ┆           ┆           ┆   ┆ cable     ┆          ┆ nteractio ┆ 4         │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ n         ┆ 21:18:50  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [8]:
df_funnel_original.filter(pl.col("client_id") == 120)

shape: (2, 28)
┌────────────┬────────────┬────────────┬───────────┬───┬───────┬───────────┬───────────┬───────────┐
│ fecha_clie ┆ fecha_crea ┆ fecha_visi ┆ fecha_vis ┆ … ┆ flujo ┆ event_nam ┆ profiling ┆ lead_rele │
│ nte        ┆ cion_proye ┆ ta_creada  ┆ ita_cread ┆   ┆ ---   ┆ e         ┆ _complete ┆ vant_id   │
│ ---        ┆ cto        ┆ ---        ┆ a_por_pro ┆   ┆ str   ┆ ---       ┆ d_at      ┆ ---       │
│ date       ┆ ---        ┆ date       ┆ yec…      ┆   ┆       ┆ str       ┆ ---       ┆ i32       │
│            ┆ date       ┆            ┆ ---       ┆   ┆       ┆           ┆ datetime[ ┆           │
│            ┆            ┆            ┆ date      ┆   ┆       ┆           ┆ μs]       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════╪═══════════╪═══════════╪═══════════╡
│ 2024-01-03 ┆ 2024-01-03 ┆ 2024-02-06 ┆ 2024-01-0 ┆ … ┆ null  ┆ null      ┆ null      ┆ 1         │
│            ┆            ┆            ┆ 3         ┆   ┆       ┆           ┆           ┆           │
│ 2024-01-03 ┆ 2024-01-03 ┆ 2024-03-05 ┆ 2024-01-0 ┆ … ┆ null  ┆ null      ┆ null      ┆ 1         │
│            ┆            ┆            ┆ 3         ┆   ┆       ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴───────┴───────────┴───────────┴───────────┘

In [11]:
df_profiles

shape: (21_784, 3)
┌─────────┬────────────────────────┬─────────────────────┐
│ user_id ┆ user_industria_role_id ┆ user_industria_role │
│ ---     ┆ ---                    ┆ ---                 │
│ i64     ┆ i64                    ┆ str                 │
╞═════════╪════════════════════════╪═════════════════════╡
│ 1       ┆ 2                      ┆ Broker              │
│ 2       ┆ 1                      ┆ Tenant              │
│ 3       ┆ 2                      ┆ Broker              │
│ 4       ┆ 2                      ┆ Broker              │
│ 5       ┆ 2                      ┆ Broker              │
│ …       ┆ …                      ┆ …                   │
│ 22187   ┆ 1                      ┆ Tenant              │
│ 22188   ┆ 4                      ┆ Landlord            │
│ 22189   ┆ 1                      ┆ Tenant              │
│ 22190   ┆ 1                      ┆ Tenant              │
│ 22191   ┆ 4                      ┆ Landlord            │
└─────────┴────────────────────────┴─────────────────────┘

In [14]:
df_alg_contract

shape: (858, 15)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ alg_id   ┆ project_i ┆ alg_event ┆ alg_loi_e ┆ … ┆ alg_creat ┆ alg_creat ┆ alg_updat ┆ alg_updat │
│ ---      ┆ d         ┆ ---       ┆ vent_id   ┆   ┆ ed_at     ┆ ed_date   ┆ ed_at     ┆ ed_date   │
│ i64      ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ str       ┆           ┆ i32       ┆   ┆ datetime[ ┆ date      ┆ datetime[ ┆ date      │
│          ┆           ┆           ┆           ┆   ┆ μs]       ┆           ┆ μs]       ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2258627  ┆ 165       ┆ projectSp ┆ 1         ┆ … ┆ 2024-01-0 ┆ 2024-01-0 ┆ 2024-01-0 ┆ 2024-01-0 │
│          ┆           ┆ otContrac ┆           ┆   ┆ 3         ┆ 3         ┆ 3         ┆ 3         │
│          ┆           ┆ t         ┆           ┆   ┆ 17:33:19  ┆           ┆ 17:33:19  ┆           │
│ 2280334  ┆ 308       ┆ projectSp ┆ 1         ┆ … ┆ 2024-01-0 ┆ 2024-01-0 ┆ 2024-01-0 ┆ 2024-01-0 │
│          ┆           ┆ otContrac ┆           ┆   ┆ 5         ┆ 5         ┆ 5         ┆ 5         │
│          ┆           ┆ t         ┆           ┆   ┆ 10:07:15  ┆           ┆ 10:07:15  ┆           │
│ 2280464  ┆ 307       ┆ projectSp ┆ 1         ┆ … ┆ 2024-01-0 ┆ 2024-01-0 ┆ 2024-01-0 ┆ 2024-01-0 │
│          ┆           ┆ otContrac ┆           ┆   ┆ 5         ┆ 5         ┆ 5         ┆ 5         │
│          ┆           ┆ t         ┆           ┆   ┆ 10:19:49  ┆           ┆ 10:19:49  ┆           │
│ 2312608  ┆ 142       ┆ projectSp ┆ 1         ┆ … ┆ 2024-01-0 ┆ 2024-01-0 ┆ 2024-01-0 ┆ 2024-01-0 │
│          ┆           ┆ otContrac ┆           ┆   ┆ 8         ┆ 8         ┆ 8         ┆ 8         │
│          ┆           ┆ t         ┆           ┆   ┆ 17:30:15  ┆           ┆ 17:30:15  ┆           │
│ 2339214  ┆ 223       ┆ projectSp ┆ 1         ┆ … ┆ 2024-01-1 ┆ 2024-01-1 ┆ 2024-01-1 ┆ 2024-01-1 │
│          ┆           ┆ otContrac ┆           ┆   ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│          ┆           ┆ t         ┆           ┆   ┆ 13:31:36  ┆           ┆ 13:31:36  ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 38958108 ┆ 18981     ┆ projectSp ┆ 1         ┆ … ┆ 2025-12-0 ┆ 2025-12-0 ┆ 2025-12-0 ┆ 2025-12-0 │
│          ┆           ┆ otWon     ┆           ┆   ┆ 4         ┆ 4         ┆ 4         ┆ 4         │
│          ┆           ┆           ┆           ┆   ┆ 10:00:15  ┆           ┆ 10:00:15  ┆           │
│ 39212210 ┆ 20626     ┆ projectSp ┆ 1         ┆ … ┆ 2025-12-0 ┆ 2025-12-0 ┆ 2025-12-0 ┆ 2025-12-0 │
│          ┆           ┆ otWon     ┆           ┆   ┆ 8         ┆ 8         ┆ 8         ┆ 8         │
│          ┆           ┆           ┆           ┆   ┆ 10:51:25  ┆           ┆ 10:51:25  ┆           │
│ 39228974 ┆ 18157     ┆ projectSp ┆ 1         ┆ … ┆ 2025-12-0 ┆ 2025-12-0 ┆ 2025-12-0 ┆ 2025-12-0 │
│          ┆           ┆ otWon     ┆           ┆   ┆ 8         ┆ 8         ┆ 8         ┆ 8         │
│          ┆           ┆           ┆           ┆   ┆ 16:08:20  ┆           ┆ 16:08:20  ┆           │
│ 39270060 ┆ 17522     ┆ projectSp ┆ 1         ┆ … ┆ 2025-12-0 ┆ 2025-12-0 ┆ 2025-12-0 ┆ 2025-12-0 │
│          ┆           ┆ otWon     ┆           ┆   ┆ 9         ┆ 9         ┆ 9         ┆ 9         │
│          ┆           ┆           ┆           ┆   ┆ 13:20:31  ┆           ┆ 13:20:31  ┆           │
│ 39473159 ┆ 19058     ┆ projectSp ┆ 1         ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 │
│          ┆           ┆ otWon     ┆           ┆   ┆ 2         ┆ 2         ┆ 2         ┆ 2         │
│          ┆           ┆           ┆           ┆   ┆ 11:22:12  ┆           ┆ 11:22:12  ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
stg_s2p_leads.columns

['lead_id',
 'lead_name',
 'lead_last_name',
 'lead_mothers_last_name',
 'lead_email',
 'lead_domain',
 'lead_phone_indicator',
 'lead_phone_number',
 'lead_full_phone_number',
 'lead_company',
 'lead_position',
 'lead_origin_id',
 'lead_origin',
 'lead_l0',
 'lead_l1',
 'lead_l2',
 'lead_l3',
 'lead_l4',
 'lead_supply',
 'lead_s0',
 'lead_s1',
 'lead_s3',
 'lead_max_type_id',
 'lead_max_type',
 'lead_client_type_id',
 'lead_client_type',
 'user_id',
 'agent_id',
 'lead_agent_by_api',
 'agent_kam_id',
 'spot_sector_id',
 'spot_sector',
 'lead_status_id',
 'lead_status',
 'lead_first_contact_time',
 'spot_min_square_space',
 'spot_max_square_space',
 'lead_sourse_id',
 'lead_sourse',
 'lead_hs_first_conversion',
 'lead_hs_utm_campaign',
 'lead_campaign_type_id',
 'lead_campaign_type',
 'lead_hs_analytics_source_data_1',
 'lead_hs_recent_conversion',
 'lead_hs_recent_conversion_date',
 'lead_hs_industrial_profiling',
 'lead_industrial_profile_state',
 'lead_industrial_profile_zone',
 'lead_industrial_profile_size_id',
 'lead_industrial_profile_size',
 'lead_industrial_profile_budget_id',
 'lead_industrial_profile_budget',
 'lead_hs_office_profiling',
 'lead_office_profile_state',
 'lead_office_profile_zone',
 'lead_office_profile_size_id',
 'lead_office_profile_size',
 'lead_office_profile_budget_id',
 'lead_office_profile_budget',
 'lead_relevant_id',
 'lead_relevant',
 'lead_lead0_at',
 'lead_lead1_at',
 'lead_lead2_at',
 'lead_lead3_at',
 'lead_lead4_at',
 'lead_supply_at',
 'lead_supply0_at',
 'lead_supply1_at',
 'lead_supply3_at',
 'lead_client_at',
 'lead_type_date_start',
 'lead_profiling_completed_at',
 'lead_created_at',
 'lead_created_date',
 'lead_updated_at',
 'lead_updated_date',
 'lead_deleted_at',
 'lead_deleted_date']

In [10]:
df_leads = stg_s2p_leads #.filter(pl.col("lead_relevant_id") == 1)
df_user_profiles = stg_s2p_user_profiles.select(
    ["user_id", "user_industria_role_id", "user_industria_role"]
)
df_leads = df_leads.join(df_user_profiles, on="user_id", how="left")
df_leads

shape: (60_114, 82)
┌─────────┬───────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ lead_id ┆ lead_name ┆ lead_last_ ┆ lead_moth ┆ … ┆ lead_dele ┆ lead_dele ┆ user_indu ┆ user_indu │
│ ---     ┆ ---       ┆ name       ┆ ers_last_ ┆   ┆ ted_at    ┆ ted_date  ┆ stria_rol ┆ stria_rol │
│ i64     ┆ str       ┆ ---        ┆ name      ┆   ┆ ---       ┆ ---       ┆ e_id      ┆ e         │
│         ┆           ┆ str        ┆ ---       ┆   ┆ datetime[ ┆ date      ┆ ---       ┆ ---       │
│         ┆           ┆            ┆ str       ┆   ┆ μs]       ┆           ┆ i64       ┆ str       │
╞═════════╪═══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1       ┆ Pedro     ┆ Santana    ┆ null      ┆ … ┆ 2024-03-2 ┆ 2024-03-2 ┆ 2         ┆ Broker    │
│         ┆           ┆            ┆           ┆   ┆ 5         ┆ 5         ┆           ┆           │
│         ┆           ┆            ┆           ┆   ┆ 13:21:48  ┆           ┆           ┆           │
│ 2       ┆ Pedro     ┆ Santana    ┆ null      ┆ … ┆ 2024-03-2 ┆ 2024-03-2 ┆ 2         ┆ Broker    │
│         ┆           ┆            ┆           ┆   ┆ 5         ┆ 5         ┆           ┆           │
│         ┆           ┆            ┆           ┆   ┆ 13:21:48  ┆           ┆           ┆           │
│ 3       ┆ Pedro     ┆ Santana    ┆ null      ┆ … ┆ 2024-03-2 ┆ 2024-03-2 ┆ 2         ┆ Broker    │
│         ┆           ┆            ┆           ┆   ┆ 5         ┆ 5         ┆           ┆           │
│         ┆           ┆            ┆           ┆   ┆ 13:21:48  ┆           ┆           ┆           │
│ 4       ┆ Alex      ┆ H          ┆ null      ┆ … ┆ 2024-03-2 ┆ 2024-03-2 ┆ 2         ┆ Broker    │
│         ┆           ┆            ┆           ┆   ┆ 7         ┆ 7         ┆           ┆           │
│         ┆           ┆            ┆           ┆   ┆ 13:11:33  ┆           ┆           ┆           │
│ 5       ┆ Diego     ┆ Garcia     ┆ null      ┆ … ┆ 2024-03-2 ┆ 2024-03-2 ┆ null      ┆ null      │
│         ┆           ┆            ┆           ┆   ┆ 7         ┆ 7         ┆           ┆           │
│         ┆           ┆            ┆           ┆   ┆ 13:11:33  ┆           ┆           ┆           │
│ …       ┆ …         ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 60162   ┆ Evelin    ┆ null       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 60163   ┆ Gisela    ┆ Baeza      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 60164   ┆ ADRIANA   ┆ VALDEZ     ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 60165   ┆ Blanca    ┆ null       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 60166   ┆           ┆ null       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└─────────┴───────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [3]:
df2 = execute_asset("core_lk_projects", partition_key="2024-12-01")
df2

🔗 Resolviendo dependencias para core_lk_projects: ['stg_s2p_projects', 'stg_s2p_leads', 'stg_s2p_user_profiles', 'core_project_funnel']
🔗 Resolviendo dependencias para stg_s2p_projects: ['raw_s2p_project_requirements']

2025-12-15 22:28:43 -0600 - dagster - INFO - system - Using schema overrides for 40 columns
2025-12-15 22:28:45 -0600 - dagster - INFO - system - Extracted 19037 rows from MySQL (polars read_database with schema)
2025-12-15 22:28:45 -0600 - dagster - INFO - system - raw_s2p_project_requirements: 19037 rows for 2024-12-01
2025-12-15 22:28:45 -0600 - dagster - INFO - system - stg_s2p_projects: 19037 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_leads: ['raw_s2p_clients']

2025-12-15 22:28:46 -0600 - dagster - INFO - system - Using schema overrides for 89 columns
2025-12-15 22:28:48 -0600 - dagster - INFO - system - Extracted 60315 rows from MySQL (polars read_database with schema)
2025-12-15 22:28:48 -0600 - dagster - INFO - system - raw_s2p_clients: 60315 rows for 2024-12-01
2025-12-15 22:28:49 -0600 - dagster - INFO - system - stg_s2p_leads: 60315 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_user_profiles: ['raw_s2p_profiles']

2025-12-15 22:28:50 -0600 - dagster - INFO - system - Using schema overrides for 22 columns
2025-12-15 22:28:51 -0600 - dagster - INFO - system - Extracted 21797 rows from MySQL (polars read_database with schema)
2025-12-15 22:28:51 -0600 - dagster - INFO - system - raw_s2p_profiles: 21797 rows for 2024-12-01
2025-12-15 22:28:51 -0600 - dagster - INFO - system - stg_s2p_user_profiles: 21796 rows for partition 2024-12-01

🔗 Resolviendo dependencias para core_project_funnel: ['stg_s2p_leads', 'stg_s2p_projects', 'stg_s2p_appointments', 'stg_s2p_apd_appointment_dates', 'stg_s2p_alg_activity_log_projects', 'stg_s2p_leh_lead_event_histories']
🔄 Usando resultado cacheado para stg_s2p_leads
🔄 Usando resultado cacheado para stg_s2p_projects
🔗 Resolviendo dependencias para stg_s2p_appointments: ['raw_s2p_calendar_appointments']

2025-12-15 22:28:52 -0600 - dagster - INFO - system - Using schema overrides for 15 columns
2025-12-15 22:28:53 -0600 - dagster - INFO - system - Extracted 6128 rows from MySQL (polars read_database with schema)
2025-12-15 22:28:53 -0600 - dagster - INFO - system - raw_s2p_calendar_appointments: 6128 rows for 2024-12-01
2025-12-15 22:28:53 -0600 - dagster - INFO - system - stg_s2p_appointments: 6128 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_apd_appointment_dates: ['raw_s2p_calendar_appointment_dates']

2025-12-15 22:28:55 -0600 - dagster - INFO - system - Using schema overrides for 15 columns
2025-12-15 22:28:58 -0600 - dagster - INFO - system - Extracted 9074 rows from MySQL (polars read_database with schema)
2025-12-15 22:28:58 -0600 - dagster - INFO - system - raw_s2p_calendar_appointment_dates: 9074 rows for 2024-12-01
2025-12-15 22:28:58 -0600 - dagster - INFO - system - stg_s2p_apd_appointment_dates: 9074 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_alg_activity_log_projects: ['raw_s2p_activity_log_projects']

2025-12-15 22:28:59 -0600 - dagster - INFO - system - Using schema overrides for 16 columns
2025-12-15 22:29:00 -0600 - dagster - INFO - system - Extracted 2392 rows from MySQL (polars read_database with schema)
2025-12-15 22:29:00 -0600 - dagster - INFO - system - raw_s2p_activity_log_projects: 2392 rows for 2024-12-01
2025-12-15 22:29:00 -0600 - dagster - INFO - system - stg_s2p_alg_activity_log_projects: 2392 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_leh_lead_event_histories: ['raw_s2p_client_event_histories']

2025-12-15 22:29:01 -0600 - dagster - INFO - system - Using schema overrides for 9 columns
2025-12-15 22:29:03 -0600 - dagster - INFO - system - Extracted 100645 rows from MySQL (polars read_database with schema)
2025-12-15 22:29:03 -0600 - dagster - INFO - system - raw_s2p_client_event_histories: 100645 rows for 2024-12-01
2025-12-15 22:29:03 -0600 - dagster - INFO - system - stg_s2p_leh_lead_event_histories: 100645 rows for partition 2024-12-01
2025-12-15 22:29:03 -0600 - dagster - INFO - system - core_project_funnel: 38472 rows for partition 2024-12-01
2025-12-15 22:29:03 -0600 - dagster - INFO - system - core_lk_projects: 19099 rows for partition 2024-12-01

shape: (19_099, 63)
┌────────────┬───────────┬─────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ project_id ┆ project_n ┆ lead_id ┆ spot_sect ┆ … ┆ aud_inser ┆ aud_updat ┆ aud_updat ┆ aud_job   │
│ ---        ┆ ame       ┆ ---     ┆ or        ┆   ┆ ted_date  ┆ ed_at     ┆ ed_date   ┆ ---       │
│ i64        ┆ ---       ┆ i64     ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str       │
│            ┆ str       ┆         ┆ str       ┆   ┆ date      ┆ datetime[ ┆ date      ┆           │
│            ┆           ┆         ┆           ┆   ┆           ┆ μs]       ┆           ┆           │
╞════════════╪═══════════╪═════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 21         ┆ talo      ┆ 15      ┆ Retail    ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ proyect   ┆         ┆           ┆   ┆ 5         ┆ 5 22:29:0 ┆ 5         ┆ ts        │
│            ┆           ┆         ┆           ┆   ┆           ┆ 3.507088  ┆           ┆           │
│ 22         ┆ natalia   ┆ 15      ┆ Retail    ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ montes 1  ┆         ┆           ┆   ┆ 5         ┆ 5 22:29:0 ┆ 5         ┆ ts        │
│            ┆           ┆         ┆           ┆   ┆           ┆ 3.507088  ┆           ┆           │
│ 26         ┆ Le        ┆ 17      ┆ Retail    ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ Creuset   ┆         ┆           ┆   ┆ 5         ┆ 5 22:29:0 ┆ 5         ┆ ts        │
│            ┆           ┆         ┆           ┆   ┆           ┆ 3.507088  ┆           ┆           │
│ 28         ┆ IMEXC     ┆ 19      ┆ Industria ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆           ┆         ┆ l         ┆   ┆ 5         ┆ 5 22:29:0 ┆ 5         ┆ ts        │
│            ┆           ┆         ┆           ┆   ┆           ┆ 3.507088  ┆           ┆           │
│ 30         ┆ Novag     ┆ 20      ┆ Industria ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆           ┆         ┆ l         ┆   ┆ 5         ┆ 5 22:29:0 ┆ 5         ┆ ts        │
│            ┆           ┆         ┆           ┆   ┆           ┆ 3.507088  ┆           ┆           │
│ …          ┆ …         ┆ …       ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 21809      ┆ L2        ┆ 60363   ┆ Retail    ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ 15/12/25  ┆         ┆           ┆   ┆ 5         ┆ 5 22:29:0 ┆ 5         ┆ ts        │
│            ┆ María     ┆         ┆           ┆   ┆           ┆ 3.507088  ┆           ┆           │
│ 21810      ┆ L2        ┆ 60364   ┆ Office    ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ 15/12/25  ┆         ┆           ┆   ┆ 5         ┆ 5 22:29:0 ┆ 5         ┆ ts        │
│            ┆ Heredia   ┆         ┆           ┆   ┆           ┆ 3.507088  ┆           ┆           │
│ 21811      ┆ L2        ┆ 60365   ┆ Retail    ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ 15/12/25  ┆         ┆           ┆   ┆ 5         ┆ 5 22:29:0 ┆ 5         ┆ ts        │
│            ┆           ┆         ┆           ┆   ┆           ┆ 3.507088  ┆           ┆           │
│ 21812      ┆ L2        ┆ 60366   ┆ Land      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ 15/12/25  ┆         ┆           ┆   ┆ 5         ┆ 5 22:29:0 ┆ 5         ┆ ts        │
│            ┆ Pako      ┆         ┆           ┆   ┆           ┆ 3.507088  ┆           ┆           │
│ 21813      ┆ L2        ┆ 60367   ┆ Office    ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ 15/12/25  ┆         ┆           ┆   ┆ 5         ┆ 5 22:29:0 ┆ 5         ┆ ts        │
│            ┆ Bren      ┆         ┆           ┆   ┆           ┆ 3.507088  ┆           ┆           │
└────────────┴───────────┴─────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [3]:
execute_asset("lk_projects_to_geospot", partition_key="2026-01-07")

🔗 Resolviendo dependencias para lk_projects_to_geospot: ['lk_projects_to_s3']
🔗 Resolviendo dependencias para lk_projects_to_s3: ['gold_lk_projects']
🔗 Resolviendo dependencias para gold_lk_projects: ['stg_s2p_projects', 'stg_s2p_leads', 'stg_s2p_user_profiles', 'core_project_funnel']
🔗 Resolviendo dependencias para stg_s2p_projects: ['raw_s2p_project_requirements']

2026-01-07 18:47:19 -0600 - dagster - INFO - system - Using schema overrides for 40 columns
2026-01-07 18:47:21 -0600 - dagster - INFO - system - Extracted 19835 rows from MySQL (polars read_database with schema)
2026-01-07 18:47:21 -0600 - dagster - INFO - system - raw_s2p_project_requirements: 19835 rows for 2026-01-07
2026-01-07 18:47:21 -0600 - dagster - INFO - system - stg_s2p_projects: 19835 rows for partition 2026-01-07

🔗 Resolviendo dependencias para stg_s2p_leads: ['raw_s2p_clients']

2026-01-07 18:47:22 -0600 - dagster - INFO - system - Using schema overrides for 89 columns
2026-01-07 18:47:25 -0600 - dagster - INFO - system - Extracted 61087 rows from MySQL (polars read_database with schema)
2026-01-07 18:47:25 -0600 - dagster - INFO - system - raw_s2p_clients: 61087 rows for 2026-01-07
2026-01-07 18:47:25 -0600 - dagster - INFO - system - stg_s2p_leads: 61087 rows for partition 2026-01-07

🔗 Resolviendo dependencias para stg_s2p_user_profiles: ['raw_s2p_profiles']

2026-01-07 18:47:28 -0600 - dagster - INFO - system - Using schema overrides for 22 columns
2026-01-07 18:47:29 -0600 - dagster - INFO - system - Extracted 21929 rows from MySQL (polars read_database with schema)
2026-01-07 18:47:29 -0600 - dagster - INFO - system - raw_s2p_profiles: 21929 rows for 2026-01-07
2026-01-07 18:47:29 -0600 - dagster - INFO - system - stg_s2p_user_profiles: 21928 rows for partition 2026-01-07

🔗 Resolviendo dependencias para core_project_funnel: ['stg_s2p_leads', 'stg_s2p_projects', 'stg_s2p_appointments', 'stg_s2p_apd_appointment_dates', 'stg_s2p_alg_activity_log_projects', 'stg_s2p_leh_lead_event_histories']
🔄 Usando resultado cacheado para stg_s2p_leads
🔄 Usando resultado cacheado para stg_s2p_projects
🔗 Resolviendo dependencias para stg_s2p_appointments: ['raw_s2p_calendar_appointments']

2026-01-07 18:47:30 -0600 - dagster - INFO - system - Using schema overrides for 15 columns
2026-01-07 18:47:33 -0600 - dagster - INFO - system - Extracted 6315 rows from MySQL (polars read_database with schema)
2026-01-07 18:47:33 -0600 - dagster - INFO - system - raw_s2p_calendar_appointments: 6315 rows for 2026-01-07
2026-01-07 18:47:33 -0600 - dagster - INFO - system - stg_s2p_appointments: 6315 rows for partition 2026-01-07

🔗 Resolviendo dependencias para stg_s2p_apd_appointment_dates: ['raw_s2p_calendar_appointment_dates']

2026-01-07 18:47:35 -0600 - dagster - INFO - system - Using schema overrides for 15 columns
2026-01-07 18:47:36 -0600 - dagster - INFO - system - Extracted 9309 rows from MySQL (polars read_database with schema)
2026-01-07 18:47:36 -0600 - dagster - INFO - system - raw_s2p_calendar_appointment_dates: 9309 rows for 2026-01-07
2026-01-07 18:47:36 -0600 - dagster - INFO - system - stg_s2p_apd_appointment_dates: 9309 rows for partition 2026-01-07

🔗 Resolviendo dependencias para stg_s2p_alg_activity_log_projects: ['raw_s2p_activity_log_projects']

2026-01-07 18:47:37 -0600 - dagster - INFO - system - Using schema overrides for 16 columns
2026-01-07 18:47:39 -0600 - dagster - INFO - system - Extracted 2476 rows from MySQL (polars read_database with schema)
2026-01-07 18:47:39 -0600 - dagster - INFO - system - raw_s2p_activity_log_projects: 2476 rows for 2026-01-07
2026-01-07 18:47:39 -0600 - dagster - INFO - system - stg_s2p_alg_activity_log_projects: 2476 rows for partition 2026-01-07

🔗 Resolviendo dependencias para stg_s2p_leh_lead_event_histories: ['raw_s2p_client_event_histories']

2026-01-07 18:47:40 -0600 - dagster - INFO - system - Using schema overrides for 9 columns
2026-01-07 18:47:42 -0600 - dagster - INFO - system - Extracted 107922 rows from MySQL (polars read_database with schema)
2026-01-07 18:47:42 -0600 - dagster - INFO - system - raw_s2p_client_event_histories: 107922 rows for 2026-01-07
2026-01-07 18:47:42 -0600 - dagster - INFO - system - stg_s2p_leh_lead_event_histories: 107922 rows for partition 2026-01-07
2026-01-07 18:47:42 -0600 - dagster - INFO - system - core_project_funnel: 39290 rows for partition 2026-01-07
2026-01-07 18:47:42 -0600 - dagster - INFO - system - gold_lk_projects: 19835 rows for partition 2026-01-07
2026-01-07 18:47:43 -0600 - dagster - INFO - system - Saved 19835 records (csv) at s3://dagster-assets-production/data_lakehouse/gold/lk_projects/year=2026/month=01/day=07/data.csv
2026-01-07 18:47:43 -0600 - dagster - INFO - system - Metadata: s3_key=data_lakehouse/gold/lk_projects/year=2026/month=01/day=07/data.csv, rows=19835
2026-01-07 18:47:43 -0600 - dagster - INFO - system - Sending load request to Geospot:
  endpoint: https://geospot.spot2.mx/data-lake-house/dagster/
  payload: {'bucket_name': 'dagster-assets-production', 's3_key': 'data_lakehouse/gold/lk_projects/year=2026/month=01/day=07/data.csv', 'table_name': 'lk_projects_v2', 'mode': 'replace'}
2026-01-07 18:47:44 -0600 - dagster - INFO - system - Geospot API response:
  status_code: 200
  headers: {'Date': 'Thu, 08 Jan 2026 00:47:44 GMT', 'Content-Type': 'application/json', 'Content-Length': '61', 'Connection': 'keep-alive', 'Server': 'nginx/1.18.0 (Ubuntu)', 'Vary': 'Accept, Cookie, Origin', 'Allow': 'POST, OPTIONS', 'X-Frame-Options': 'DENY', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'same-origin', 'Cross-Origin-Opener-Policy': 'same-origin'}
  body: {"message":"Inserting data from S3 to Postgres in progress."}
2026-01-07 18:47:44 -0600 - dagster - INFO - system - Geospot API parsed response: {'message': 'Inserting data from S3 to Postgres in progress.'}
2026-01-07 18:47:44 -0600 - dagster - INFO - system - Metadata: table=lk_projects_v2, s3_key=data_lakehouse/gold/lk_projects/year=2026/month=01/day=07/data.csv

'Successfully loaded lk_projects_v2 to PostgreSQL'

In [ ]:
lead_type_date_start,

In [5]:
df_leads

shape: (36_653, 80)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ lead_id ┆ lead_name  ┆ lead_last ┆ lead_moth ┆ … ┆ lead_upda ┆ lead_upda ┆ lead_dele ┆ lead_dele │
│ ---     ┆ ---        ┆ _name     ┆ ers_last_ ┆   ┆ ted_at    ┆ ted_date  ┆ ted_at    ┆ ted_date  │
│ i64     ┆ str        ┆ ---       ┆ name      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆            ┆ str       ┆ ---       ┆   ┆ datetime[ ┆ date      ┆ datetime[ ┆ date      │
│         ┆            ┆           ┆ str       ┆   ┆ μs]       ┆           ┆ μs]       ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 112     ┆ Arturo     ┆ Márquez   ┆ null      ┆ … ┆ 2025-07-1 ┆ 2025-07-1 ┆ null      ┆ null      │
│         ┆            ┆           ┆           ┆   ┆ 4         ┆ 4         ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆ 16:43:45  ┆           ┆           ┆           │
│ 113     ┆ Karla      ┆ Cárdenas  ┆ null      ┆ … ┆ 2025-07-1 ┆ 2025-07-1 ┆ null      ┆ null      │
│         ┆            ┆           ┆           ┆   ┆ 4         ┆ 4         ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆ 16:43:46  ┆           ┆           ┆           │
│ 114     ┆ Gabriela   ┆ .         ┆ null      ┆ … ┆ 2025-07-1 ┆ 2025-07-1 ┆ null      ┆ null      │
│         ┆            ┆           ┆           ┆   ┆ 4         ┆ 4         ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆ 16:46:55  ┆           ┆           ┆           │
│ 115     ┆ Luis       ┆ Lara      ┆ Valdovino ┆ … ┆ 2025-07-1 ┆ 2025-07-1 ┆ null      ┆ null      │
│         ┆ Manuel     ┆           ┆ s         ┆   ┆ 4         ┆ 4         ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆ 16:43:46  ┆           ┆           ┆           │
│ 116     ┆ Estefany   ┆ Mendoza   ┆ Olvera    ┆ … ┆ 2025-07-1 ┆ 2025-07-1 ┆ null      ┆ null      │
│         ┆            ┆           ┆           ┆   ┆ 4         ┆ 4         ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆ 16:56:36  ┆           ┆           ┆           │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 60162   ┆ Evelin     ┆ null      ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      │
│         ┆            ┆           ┆           ┆   ┆ 0         ┆ 0         ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆ 15:44:01  ┆           ┆           ┆           │
│ 60163   ┆ Gisela     ┆ Baeza     ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      │
│         ┆            ┆           ┆           ┆   ┆ 0         ┆ 0         ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆ 16:38:53  ┆           ┆           ┆           │
│ 60164   ┆ ADRIANA    ┆ VALDEZ    ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      │
│         ┆            ┆           ┆           ┆   ┆ 0         ┆ 0         ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆ 16:45:20  ┆           ┆           ┆           │
│ 60165   ┆ Blanca     ┆ null      ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      │
│         ┆            ┆           ┆           ┆   ┆ 0         ┆ 0         ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆ 16:50:01  ┆           ┆           ┆           │
│ 60166   ┆            ┆ null      ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      │
│         ┆            ┆           ┆           ┆   ┆ 0         ┆ 0         ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆ 17:04:31  ┆           ┆           ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
df = execute_asset("core_project_funnel", partition_key="2024-12-01")
# Agregar campos constantes de auditoría
import polars as pl

aud_inserted_at_str = "2025-12-15 08:17:34.726521"
aud_inserted_date_str = "2025-12-15"
aud_updated_at_str = "2025-12-15 08:17:55.183409"
aud_updated_date_str = "2025-12-15"
aud_job_str = "lk_projects"

# La versión moderna de polars ha cambiado el argumento a "date_format" y "time_format"
# Pero para .str.strptime(), simplemente usa "format" como argumento 
# Referencia: https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.str.strptime.html

df = df.with_columns([
    pl.lit(aud_inserted_at_str).str.strptime(pl.Datetime("ms"), format="%Y-%m-%d %H:%M:%S%.f").alias("aud_inserted_at"),
    pl.lit(aud_inserted_date_str).str.strptime(pl.Date, format="%Y-%m-%d").alias("aud_inserted_date"),
    pl.lit(aud_updated_at_str).str.strptime(pl.Datetime("ms"), format="%Y-%m-%d %H:%M:%S%.f").alias("aud_updated_at"),
    pl.lit(aud_updated_date_str).str.strptime(pl.Date, format="%Y-%m-%d").alias("aud_updated_date"),
    pl.lit(aud_job_str).alias("aud_job"),
])

# Guardar el DataFrame como archivo CSV
# Exportar el DataFrame a CSV sin convertir nulls en cadenas vacías
# En polars, por default, los nulls quedan como '', lo que da problema con PostgreSQL
# Solución: serializar a csv usando null_value="\\N" (el default de psql/copy), o usar otra convención que no sea cadena vacía ni comillas

#df.write_csv("lpf_lead_project_funnel.csv")
df

🔗 Resolviendo dependencias para core_project_funnel: ['stg_s2p_leads', 'stg_s2p_projects', 'stg_s2p_appointments', 'stg_s2p_apd_appointment_dates', 'stg_s2p_alg_activity_log_projects', 'stg_s2p_leh_lead_event_histories']
🔗 Resolviendo dependencias para stg_s2p_leads: ['raw_s2p_clients']

2025-12-15 15:30:19 -0600 - dagster - INFO - system - Using schema overrides for 89 columns
2025-12-15 15:30:22 -0600 - dagster - INFO - system - Extracted 60294 rows from MySQL (polars read_database with schema)
2025-12-15 15:30:22 -0600 - dagster - INFO - system - raw_s2p_clients: 60294 rows for 2024-12-01
2025-12-15 15:30:22 -0600 - dagster - INFO - system - stg_s2p_leads: 60294 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_projects: ['raw_s2p_project_requirements']

2025-12-15 15:30:23 -0600 - dagster - INFO - system - Using schema overrides for 40 columns
2025-12-15 15:30:25 -0600 - dagster - INFO - system - Extracted 19015 rows from MySQL (polars read_database with schema)
2025-12-15 15:30:25 -0600 - dagster - INFO - system - raw_s2p_project_requirements: 19015 rows for 2024-12-01
2025-12-15 15:30:25 -0600 - dagster - INFO - system - stg_s2p_projects: 19015 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_appointments: ['raw_s2p_calendar_appointments']

2025-12-15 15:30:26 -0600 - dagster - INFO - system - Using schema overrides for 15 columns
2025-12-15 15:30:27 -0600 - dagster - INFO - system - Extracted 6122 rows from MySQL (polars read_database with schema)
2025-12-15 15:30:27 -0600 - dagster - INFO - system - raw_s2p_calendar_appointments: 6122 rows for 2024-12-01
2025-12-15 15:30:27 -0600 - dagster - INFO - system - stg_s2p_appointments: 6122 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_apd_appointment_dates: ['raw_s2p_calendar_appointment_dates']

2025-12-15 15:30:28 -0600 - dagster - INFO - system - Using schema overrides for 15 columns
2025-12-15 15:30:29 -0600 - dagster - INFO - system - Extracted 9067 rows from MySQL (polars read_database with schema)
2025-12-15 15:30:29 -0600 - dagster - INFO - system - raw_s2p_calendar_appointment_dates: 9067 rows for 2024-12-01
2025-12-15 15:30:29 -0600 - dagster - INFO - system - stg_s2p_apd_appointment_dates: 9067 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_alg_activity_log_projects: ['raw_s2p_activity_log_projects']

2025-12-15 15:30:30 -0600 - dagster - INFO - system - Using schema overrides for 16 columns
2025-12-15 15:30:32 -0600 - dagster - INFO - system - Extracted 2392 rows from MySQL (polars read_database with schema)
2025-12-15 15:30:32 -0600 - dagster - INFO - system - raw_s2p_activity_log_projects: 2392 rows for 2024-12-01
2025-12-15 15:30:32 -0600 - dagster - INFO - system - stg_s2p_alg_activity_log_projects: 2392 rows for partition 2024-12-01

🔗 Resolviendo dependencias para stg_s2p_leh_lead_event_histories: ['raw_s2p_client_event_histories']

2025-12-15 15:30:33 -0600 - dagster - INFO - system - Using schema overrides for 9 columns
2025-12-15 15:30:34 -0600 - dagster - INFO - system - Extracted 100444 rows from MySQL (polars read_database with schema)
2025-12-15 15:30:34 -0600 - dagster - INFO - system - raw_s2p_client_event_histories: 100444 rows for 2024-12-01
2025-12-15 15:30:34 -0600 - dagster - INFO - system - stg_s2p_leh_lead_event_histories: 100444 rows for partition 2024-12-01
2025-12-15 15:30:34 -0600 - dagster - INFO - system - core_project_funnel: 38448 rows for partition 2024-12-01

shape: (38_448, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ project_f ┆ project_c ┆ project_f ┆ project_f ┆ … ┆ aud_inser ┆ aud_updat ┆ aud_updat ┆ aud_job  │
│ unnel_lea ┆ reated_da ┆ unnel_vis ┆ unnel_vis ┆   ┆ ted_date  ┆ ed_at     ┆ ed_date   ┆ ---      │
│ d_date    ┆ te        ┆ it_create ┆ it_create ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│ ---       ┆ ---       ┆ d_d…      ┆ d_p…      ┆   ┆ date      ┆ datetime[ ┆ date      ┆          │
│ date      ┆ date      ┆ ---       ┆ ---       ┆   ┆           ┆ ms]       ┆           ┆          │
│           ┆           ┆ date      ┆ date      ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2024-01-0 ┆ null      ┆ null      ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_lpf_l │
│ 1         ┆           ┆           ┆           ┆   ┆ 5         ┆ 5 08:17:5 ┆ 5         ┆ ead_proj │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5.183     ┆           ┆ ect_funn │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ el       │
│ 2024-01-0 ┆ null      ┆ null      ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_lpf_l │
│ 1         ┆           ┆           ┆           ┆   ┆ 5         ┆ 5 08:17:5 ┆ 5         ┆ ead_proj │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5.183     ┆           ┆ ect_funn │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ el       │
│ 2024-01-0 ┆ null      ┆ null      ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_lpf_l │
│ 1         ┆           ┆           ┆           ┆   ┆ 5         ┆ 5 08:17:5 ┆ 5         ┆ ead_proj │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5.183     ┆           ┆ ect_funn │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ el       │
│ 2024-01-0 ┆ null      ┆ null      ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_lpf_l │
│ 1         ┆           ┆           ┆           ┆   ┆ 5         ┆ 5 08:17:5 ┆ 5         ┆ ead_proj │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5.183     ┆           ┆ ect_funn │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ el       │
│ 2024-01-0 ┆ null      ┆ null      ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_lpf_l │
│ 2         ┆           ┆           ┆           ┆   ┆ 5         ┆ 5 08:17:5 ┆ 5         ┆ ead_proj │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5.183     ┆           ┆ ect_funn │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ el       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_lpf_l │
│ 5         ┆ 5         ┆           ┆           ┆   ┆ 5         ┆ 5 08:17:5 ┆ 5         ┆ ead_proj │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5.183     ┆           ┆ ect_funn │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ el       │
│ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_lpf_l │
│ 5         ┆ 5         ┆           ┆           ┆   ┆ 5         ┆ 5 08:17:5 ┆ 5         ┆ ead_proj │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5.183     ┆           ┆ ect_funn │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ el       │
│ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_lpf_l │
│ 5         ┆ 5         ┆           ┆           ┆   ┆ 5         ┆ 5 08:17:5 ┆ 5         ┆ ead_proj │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5.183     ┆           ┆ ect_funn │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ el       │
│ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_lpf_l │
│ 5         ┆ 5         ┆           ┆           ┆   ┆ 5         ┆ 5 08:17:5 ┆ 5         ┆ ead_proj │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5.183     ┆           ┆ ect_funn │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ el       │
│ 2025-12-1 ┆ 2025-12-1 ┆ null      ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_lpf_l │
│ 5         ┆ 5         ┆           ┆           ┆   ┆ 5         ┆ 5 08:17:5 ┆ 5         ┆ ead_proj │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5.183     ┆           ┆ ect_funn │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ el       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
df.columns

['project_funnel_lead_date',
 'project_created_date',
 'project_funnel_visit_created_date',
 'project_funnel_visit_created_per_project_date',
 'appointment_id',
 'project_funnel_visit_status',
 'project_funnel_visit_realized_at',
 'project_funnel_visit_realized_per_project_date',
 'project_funnel_visit_confirmed_at',
 'project_funnel_visit_confirmed_per_project_date',
 'project_funnel_loi_date',
 'project_funnel_loi_per_project_date',
 'project_funnel_contract_date',
 'project_funnel_contract_per_project_date',
 'project_funnel_transaction_date',
 'project_funnel_transaction_per_project_date',
 'lead_id',
 'project_id',
 'project_funnel_flow',
 'project_funnel_event',
 'aud_inserted_at',
 'aud_inserted_date',
 'aud_updated_at',
 'aud_updated_date',
 'aud_job']

In [ ]:
    df_leads = (
        stg_s2p_leads
        .filter(pl.col("lead_project_funnel_relevant_id") == 1)
        .select([
            "lead_id",
            "spot_sector",
            "lead_max_type",
            "lead_campaign_type",
            "lead_profiling_completed_at",
            "lead_type_date_start",
            "lead_project_funnel_relevant_id",
        ])
        
        df_projects = (
        stg_s2p_projects
        .filter(pl.col("project_funnel_relevant_id") == 1)
        .select([
            "project_id",
            "lead_id",
            "project_last_spot_stage",
            "project_disable_reason",
            "project_won_relevant_date",
            "project_created_date",
        ])
    )

In [4]:
df_f=execute_asset("core_project_funnel", partition_key="2025-12-16")

🔄 Usando resultado cacheado para core_project_funnel

In [7]:
# Revisa si hay registros duplicados por project_id (usando Polars)
duplicate_projects = (
    df_f
    .group_by("project_id")
    .agg(pl.count().alias("count"))
    .filter(pl.col("count") > 1)
)
duplicate_projects

/tmp/ipykernel_33960/4114653310.py:5: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("count"))

shape: (67, 2)
┌────────────┬───────┐
│ project_id ┆ count │
│ ---        ┆ ---   │
│ i64        ┆ u32   │
╞════════════╪═══════╡
│ null       ┆ 19779 │
│ 21892      ┆ 3     │
│ 18891      ┆ 2     │
│ 18629      ┆ 2     │
│ 5279       ┆ 2     │
│ …          ┆ …     │
│ 18218      ┆ 2     │
│ 20317      ┆ 2     │
│ 10870      ┆ 2     │
│ 17557      ┆ 2     │
│ 18998      ┆ 2     │
└────────────┴───────┘

In [8]:
# Crea un DataFrame con los registros duplicados y agrupados por project_id
duplicate_project_ids = (
    df_f
    .group_by("project_id")
    .agg(pl.count().alias("count"))
    .filter(pl.col("count") > 1)
    .select("project_id")
)

df_f_duplicates = df_f.join(duplicate_project_ids, on="project_id", how="inner")

df_f_duplicates

/tmp/ipykernel_33960/3046732116.py:5: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("count"))

shape: (136, 20)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ project_fu ┆ project_c ┆ project_f ┆ project_f ┆ … ┆ lead_id ┆ project_i ┆ project_f ┆ project_f │
│ nnel_lead_ ┆ reated_da ┆ unnel_vis ┆ unnel_vis ┆   ┆ ---     ┆ d         ┆ unnel_flo ┆ unnel_eve │
│ date       ┆ te        ┆ it_create ┆ it_create ┆   ┆ i64     ┆ ---       ┆ w         ┆ nt        │
│ ---        ┆ ---       ┆ d_d…      ┆ d_p…      ┆   ┆         ┆ i64       ┆ ---       ┆ ---       │
│ date       ┆ date      ┆ ---       ┆ ---       ┆   ┆         ┆           ┆ str       ┆ str       │
│            ┆           ┆ date      ┆ date      ┆   ┆         ┆           ┆           ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ 2025-01-11 ┆ 2025-01-1 ┆ null      ┆ null      ┆ … ┆ 27418   ┆ 3842      ┆ Bot inter ┆ chatbotCo │
│            ┆ 1         ┆           ┆           ┆   ┆         ┆           ┆ ested     ┆ nfirmSpot │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ Interest  │
│ 2025-01-11 ┆ 2025-01-1 ┆ null      ┆ null      ┆ … ┆ 27418   ┆ 3842      ┆ Bot inter ┆ chatbotPr │
│            ┆ 1         ┆           ┆           ┆   ┆         ┆           ┆ ested     ┆ ofilingCo │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ mpleted   │
│ 2025-02-03 ┆ 2025-02-0 ┆ null      ┆ null      ┆ … ┆ 28943   ┆ 5279      ┆ Bot inter ┆ chatbotPr │
│            ┆ 3         ┆           ┆           ┆   ┆         ┆           ┆ ested     ┆ ofilingCo │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ mpleted   │
│ 2025-02-03 ┆ 2025-02-0 ┆ null      ┆ null      ┆ … ┆ 28943   ┆ 5279      ┆ Bot inter ┆ chatbotCo │
│            ┆ 3         ┆           ┆           ┆   ┆         ┆           ┆ ested     ┆ nfirmSpot │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ Interest  │
│ 2025-03-15 ┆ 2025-03-1 ┆ null      ┆ null      ┆ … ┆ 31356   ┆ 7718      ┆ Bot inter ┆ chatbotCo │
│            ┆ 5         ┆           ┆           ┆   ┆         ┆           ┆ ested     ┆ nfirmSpot │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ Interest  │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ 2025-07-05 ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ … ┆ 50668   ┆ 21702     ┆ Bot inter ┆ chatbotCo │
│            ┆ 2         ┆ 2         ┆ 2         ┆   ┆         ┆           ┆ ested     ┆ nfirmSpot │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ Interest  │
│ 2025-07-05 ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ … ┆ 50668   ┆ 21702     ┆ Bot inter ┆ chatbotPr │
│            ┆ 2         ┆ 2         ┆ 2         ┆   ┆         ┆           ┆ ested     ┆ ofilingCo │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ mpleted   │
│ 2025-04-04 ┆ 2025-12-1 ┆ null      ┆ null      ┆ … ┆ 31467   ┆ 21892     ┆ Levels    ┆ levelsCon │
│            ┆ 6         ┆           ┆           ┆   ┆         ┆           ┆ Brokers   ┆ tactEmail │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ Interacti │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ on        │
│ 2025-04-04 ┆ 2025-12-1 ┆ null      ┆ null      ┆ … ┆ 31467   ┆ 21892     ┆ Levels    ┆ levelsCon │
│            ┆ 6         ┆           ┆           ┆   ┆         ┆           ┆ Brokers   ┆ tactEmail │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ Interacti │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ on        │
│ 2025-04-04 ┆ 2025-12-1 ┆ null      ┆ null      ┆ … ┆ 31467   ┆ 21892     ┆ Levels    ┆ levelsCon │
│            ┆ 6         ┆           ┆           ┆   ┆         ┆           ┆ Brokers   ┆ tactEmail │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ Interacti │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ on        │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

In [3]:
df_p=execute_asset("core_lk_projects", partition_key="2025-12-16")

🔗 Resolviendo dependencias para core_lk_projects: ['stg_s2p_projects', 'stg_s2p_leads', 'stg_s2p_user_profiles', 'core_project_funnel']
🔗 Resolviendo dependencias para stg_s2p_projects: ['raw_s2p_project_requirements']

2025-12-17 12:35:25 -0600 - dagster - INFO - system - Using schema overrides for 40 columns
2025-12-17 12:35:27 -0600 - dagster - INFO - system - Extracted 19140 rows from MySQL (polars read_database with schema)
2025-12-17 12:35:27 -0600 - dagster - INFO - system - raw_s2p_project_requirements: 19140 rows for 2025-12-16
2025-12-17 12:35:27 -0600 - dagster - INFO - system - stg_s2p_projects: 19140 rows for partition 2025-12-16

🔗 Resolviendo dependencias para stg_s2p_leads: ['raw_s2p_clients']

2025-12-17 12:35:28 -0600 - dagster - INFO - system - Using schema overrides for 89 columns
2025-12-17 12:35:31 -0600 - dagster - INFO - system - Extracted 60407 rows from MySQL (polars read_database with schema)
2025-12-17 12:35:31 -0600 - dagster - INFO - system - raw_s2p_clients: 60407 rows for 2025-12-16
2025-12-17 12:35:31 -0600 - dagster - INFO - system - stg_s2p_leads: 60407 rows for partition 2025-12-16

🔗 Resolviendo dependencias para stg_s2p_user_profiles: ['raw_s2p_profiles']

2025-12-17 12:35:32 -0600 - dagster - INFO - system - Using schema overrides for 22 columns
2025-12-17 12:35:33 -0600 - dagster - INFO - system - Extracted 21814 rows from MySQL (polars read_database with schema)
2025-12-17 12:35:33 -0600 - dagster - INFO - system - raw_s2p_profiles: 21814 rows for 2025-12-16
2025-12-17 12:35:33 -0600 - dagster - INFO - system - stg_s2p_user_profiles: 21813 rows for partition 2025-12-16

🔗 Resolviendo dependencias para core_project_funnel: ['stg_s2p_leads', 'stg_s2p_projects', 'stg_s2p_appointments', 'stg_s2p_apd_appointment_dates', 'stg_s2p_alg_activity_log_projects', 'stg_s2p_leh_lead_event_histories']
🔄 Usando resultado cacheado para stg_s2p_leads
🔄 Usando resultado cacheado para stg_s2p_projects
🔗 Resolviendo dependencias para stg_s2p_appointments: ['raw_s2p_calendar_appointments']

2025-12-17 12:35:34 -0600 - dagster - INFO - system - Using schema overrides for 15 columns
2025-12-17 12:35:35 -0600 - dagster - INFO - system - Extracted 6164 rows from MySQL (polars read_database with schema)
2025-12-17 12:35:35 -0600 - dagster - INFO - system - raw_s2p_calendar_appointments: 6164 rows for 2025-12-16
2025-12-17 12:35:35 -0600 - dagster - INFO - system - stg_s2p_appointments: 6164 rows for partition 2025-12-16

🔗 Resolviendo dependencias para stg_s2p_apd_appointment_dates: ['raw_s2p_calendar_appointment_dates']

2025-12-17 12:35:37 -0600 - dagster - INFO - system - Using schema overrides for 15 columns
2025-12-17 12:35:38 -0600 - dagster - INFO - system - Extracted 9120 rows from MySQL (polars read_database with schema)
2025-12-17 12:35:38 -0600 - dagster - INFO - system - raw_s2p_calendar_appointment_dates: 9120 rows for 2025-12-16
2025-12-17 12:35:38 -0600 - dagster - INFO - system - stg_s2p_apd_appointment_dates: 9120 rows for partition 2025-12-16

🔗 Resolviendo dependencias para stg_s2p_alg_activity_log_projects: ['raw_s2p_activity_log_projects']

2025-12-17 12:35:39 -0600 - dagster - INFO - system - Using schema overrides for 16 columns
2025-12-17 12:35:40 -0600 - dagster - INFO - system - Extracted 2396 rows from MySQL (polars read_database with schema)
2025-12-17 12:35:40 -0600 - dagster - INFO - system - raw_s2p_activity_log_projects: 2396 rows for 2025-12-16
2025-12-17 12:35:40 -0600 - dagster - INFO - system - stg_s2p_alg_activity_log_projects: 2396 rows for partition 2025-12-16

🔗 Resolviendo dependencias para stg_s2p_leh_lead_event_histories: ['raw_s2p_client_event_histories']

2025-12-17 12:35:41 -0600 - dagster - INFO - system - Using schema overrides for 9 columns
2025-12-17 12:35:43 -0600 - dagster - INFO - system - Extracted 101818 rows from MySQL (polars read_database with schema)
2025-12-17 12:35:43 -0600 - dagster - INFO - system - raw_s2p_client_event_histories: 101818 rows for 2025-12-16
2025-12-17 12:35:43 -0600 - dagster - INFO - system - stg_s2p_leh_lead_event_histories: 101818 rows for partition 2025-12-16
2025-12-17 12:35:43 -0600 - dagster - INFO - system - core_project_funnel: 38575 rows for partition 2025-12-16
2025-12-17 12:35:43 -0600 - dagster - INFO - system - core_lk_projects: 19140 rows for partition 2025-12-16

In [4]:
df_p

shape: (19_140, 63)
┌────────────┬───────────┬─────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ project_id ┆ project_n ┆ lead_id ┆ spot_sect ┆ … ┆ aud_inser ┆ aud_updat ┆ aud_updat ┆ aud_job   │
│ ---        ┆ ame       ┆ ---     ┆ or        ┆   ┆ ted_date  ┆ ed_at     ┆ ed_date   ┆ ---       │
│ i64        ┆ ---       ┆ i64     ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str       │
│            ┆ str       ┆         ┆ str       ┆   ┆ date      ┆ datetime[ ┆ date      ┆           │
│            ┆           ┆         ┆           ┆   ┆           ┆ μs]       ┆           ┆           │
╞════════════╪═══════════╪═════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 21         ┆ talo      ┆ 15      ┆ Retail    ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ proyect   ┆         ┆           ┆   ┆ 7         ┆ 7 12:35:4 ┆ 7         ┆ ts        │
│            ┆           ┆         ┆           ┆   ┆           ┆ 3.333256  ┆           ┆           │
│ 22         ┆ natalia   ┆ 15      ┆ Retail    ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ montes 1  ┆         ┆           ┆   ┆ 7         ┆ 7 12:35:4 ┆ 7         ┆ ts        │
│            ┆           ┆         ┆           ┆   ┆           ┆ 3.333256  ┆           ┆           │
│ 26         ┆ Le        ┆ 17      ┆ Retail    ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ Creuset   ┆         ┆           ┆   ┆ 7         ┆ 7 12:35:4 ┆ 7         ┆ ts        │
│            ┆           ┆         ┆           ┆   ┆           ┆ 3.333256  ┆           ┆           │
│ 28         ┆ IMEXC     ┆ 19      ┆ Industria ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆           ┆         ┆ l         ┆   ┆ 7         ┆ 7 12:35:4 ┆ 7         ┆ ts        │
│            ┆           ┆         ┆           ┆   ┆           ┆ 3.333256  ┆           ┆           │
│ 30         ┆ Novag     ┆ 20      ┆ Industria ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆           ┆         ┆ l         ┆   ┆ 7         ┆ 7 12:35:4 ┆ 7         ┆ ts        │
│            ┆           ┆         ┆           ┆   ┆           ┆ 3.333256  ┆           ┆           │
│ …          ┆ …         ┆ …       ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 21924      ┆ L2        ┆ 16260   ┆ Retail    ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ 17/12/25  ┆         ┆           ┆   ┆ 7         ┆ 7 12:35:4 ┆ 7         ┆ ts        │
│            ┆ Capitalli ┆         ┆           ┆   ┆           ┆ 3.333256  ┆           ┆           │
│            ┆ nks       ┆         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 21925      ┆ L2        ┆ 60453   ┆ Office    ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ 17/12/25  ┆         ┆           ┆   ┆ 7         ┆ 7 12:35:4 ┆ 7         ┆ ts        │
│            ┆ Scarlett  ┆         ┆           ┆   ┆           ┆ 3.333256  ┆           ┆           │
│ 21926      ┆ L2        ┆ 60456   ┆ Industria ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ 17/12/25  ┆         ┆ l         ┆   ┆ 7         ┆ 7 12:35:4 ┆ 7         ┆ ts        │
│            ┆ Lingyu    ┆         ┆           ┆   ┆           ┆ 3.333256  ┆           ┆           │
│ 21927      ┆ L1        ┆ 60457   ┆ Industria ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ 17/12/25  ┆         ┆ l         ┆   ┆ 7         ┆ 7 12:35:4 ┆ 7         ┆ ts        │
│            ┆ REBECA    ┆         ┆           ┆   ┆           ┆ 3.333256  ┆           ┆           │
│ 21928      ┆ L2        ┆ 60459   ┆ Retail    ┆ … ┆ 2025-12-1 ┆ 2025-12-1 ┆ 2025-12-1 ┆ lk_projec │
│            ┆ 17/12/25  ┆         ┆           ┆   ┆ 7         ┆ 7 12:35:4 ┆ 7         ┆ ts        │
│            ┆ Claudia   ┆         ┆           ┆   ┆           ┆ 3.333256  ┆           ┆           │
└────────────┴───────────┴─────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
# Crear un DataFrame con los duplicados por project_id y agruparlos
import polars as pl

duplicate_project_ids_p = (
    df_p
    .group_by("project_id")
    .agg(pl.count().alias("count"))
    .filter(pl.col("count") > 1)
    .select("project_id")
)

df_p_duplicates = df_p.join(duplicate_project_ids_p, on="project_id", how="inner")

# Agrupa los duplicados por project_id (mostrar cantidad de duplicados por id como ejemplo)
df_p_grouped_duplicates = (
    df_p_duplicates
    .group_by("project_id")
    .agg([
        pl.count().alias("num_duplicates"),
        # Puedes agregar más agregaciones aquí si necesitas
    ])
)

df_p_grouped_duplicates

/tmp/ipykernel_51625/2108342958.py:7: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("count"))
/tmp/ipykernel_51625/2108342958.py:19: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("num_duplicates"),

shape: (0, 2)
┌────────────┬────────────────┐
│ project_id ┆ num_duplicates │
│ ---        ┆ ---            │
│ i64        ┆ u32            │
╞════════════╪════════════════╡
└────────────┴────────────────┘

In [6]:
# Revisa si hay registros duplicados por project_id (usando Polars)
duplicate_projects = (
    df_p
    .group_by("project_id")
    .agg(pl.count().alias("count"))
    .filter(pl.col("count") > 1)
)
duplicate_projects

/tmp/ipykernel_51625/2201747806.py:5: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("count"))

shape: (0, 2)
┌────────────┬───────┐
│ project_id ┆ count │
│ ---        ┆ ---   │
│ i64        ┆ u32   │
╞════════════╪═══════╡
└────────────┴───────┘